[build]
  command = "npm i -g pnpm --force && pnpm install && pnpm build --filter @haxvibe/web"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"
